<a href="https://colab.research.google.com/github/serinss/seSAC_Python_Class/blob/main/%ED%86%B5%EA%B3%84%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D_%EC%A3%BC%EC%9A%94_%EB%AA%A8%EB%93%88_%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

p.133 Numpy 기본

In [1]:
ls = [1,2,3,4,5]

ls_twice = []
for e in ls:
  ls_twice.append(e*2)
ls_twice

[2, 4, 6, 8, 10]

In [2]:
import numpy as np
arr = np.array(ls)
arr_twice = arr*2
arr_twice

array([ 2,  4,  6,  8, 10])

강한 wrapping

In [3]:
arr = np.arange(10000)
arr

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [4]:
arr = np.array(range(10000))
arr

array([   0,    1,    2, ..., 9997, 9998, 9999])

wrapping 이란?  
이미 만들어진 함수나 기능을 이용하여 새로운 사용자 정의 함수 생성

In [6]:
def madd(a,b):
  return a+b

In [7]:
def msum(ls):
  s = 0
  for e in ls:
    s = madd(s,e)
  return s

In [9]:
def count(ls):
  cnt = 0
  for _ in ls:
    cnt += 1
  return cnt

In [11]:
ls=[1,2,3,8,4]
s = msum(ls)
l = count(ls)
print(f"평균:{s/l:.2f}")

평균:3.60


In [10]:
def average(ls):
  return msum(ls)/count(ls)

In [12]:
print(f'평균:{average(ls):.2f}')

평균:3.60


#텐서

In [13]:
data = np.random.rand(5,2,3)
data

array([[[0.79200147, 0.20069799, 0.8133385 ],
        [0.86048908, 0.42003699, 0.45243234]],

       [[0.92695418, 0.15277495, 0.82021026],
        [0.1866429 , 0.16379641, 0.28190997]],

       [[0.90784114, 0.34914451, 0.64911809],
        [0.00565503, 0.74442918, 0.41929525]],

       [[0.66134941, 0.36166954, 0.59598824],
        [0.83791731, 0.16607717, 0.17439957]],

       [[0.41193963, 0.04329013, 0.1158357 ],
        [0.57826417, 0.51617248, 0.17085518]]])

In [14]:
data.shape

(5, 2, 3)

In [15]:
data2 = data.reshape(6,-1)
data2

array([[0.79200147, 0.20069799, 0.8133385 , 0.86048908, 0.42003699],
       [0.45243234, 0.92695418, 0.15277495, 0.82021026, 0.1866429 ],
       [0.16379641, 0.28190997, 0.90784114, 0.34914451, 0.64911809],
       [0.00565503, 0.74442918, 0.41929525, 0.66134941, 0.36166954],
       [0.59598824, 0.83791731, 0.16607717, 0.17439957, 0.41193963],
       [0.04329013, 0.1158357 , 0.57826417, 0.51617248, 0.17085518]])

In [16]:
data2.shape

(6, 5)

In [18]:
#data3 = data.reshape(7,-1) #요구하는 구조로 구조가 정확하게 구성될 수 없음
#data3

In [19]:
#파이썬의 리스트는 tensor 자료가 아닐 수 있다
zagged_arr = [[1,2,3],[1,2],[1,2,3,4,5]] #원소의 개수가 일정하지 않는 리스트
zagged_arr

[[1, 2, 3], [1, 2], [1, 2, 3, 4, 5]]

In [22]:
data2.ndim

2

In [23]:
data2.shape

(6, 5)

#행렬 계산

In [20]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[4,6],[3,7]])

arr3 = arr1 + arr2
arr3

array([[ 5,  8],
       [ 6, 11]])

In [21]:
ls1 = [[1,2],[3,4]]
ls2 = [[4,6],[3,7]]
ls3 = ls1 + ls2 #연산 X
ls3

[[1, 2], [3, 4], [4, 6], [3, 7]]

#원소 형식

In [33]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [37]:
type(arr1[0])

numpy.ndarray

In [25]:
arr = np.array([1,2,3,4,5.])
arr.dtype

dtype('float64')

In [36]:
type(arr2[0])

numpy.ndarray

In [32]:
arr3 = np.array([1,2,'a',4,5]) # 모든 원소가 같은 데이터 타입이어야 한다.
arr3.dtype

dtype('<U21')

In [35]:
type(arr3[0])

numpy.str_

In [38]:
arr3[0] #문자 1로 표현됨

'1'

In [40]:
ls = [1,2,3,4,5.] #리스트는 원소가 다 다른 타입이어도 저장된다. 
type(ls[0]),type(ls[4])

(int, float)

#형식 변환

In [45]:
arr4 = np.array(['1','2','3','4'])
for e in arr4:
  print(e,end=',')
print()

1,2,3,4,


In [49]:
s = arr4[0]
for e in range(1,len(arr4)):
  s += arr4[e] #문자열이므로 연산 X, 이어 붙이기 O
s

'1234'

In [51]:
arr5 = arr4.astype(int) #한꺼번에 해당하는 타입으로 패싱하고 싶을 때 사용
print(arr5.sum())

10


#산술 연산, 필터링

In [52]:
arr = np.array([[1,2],[3,4]])
sq_arr = arr*arr
sq_arr

array([[ 1,  4],
       [ 9, 16]])

In [53]:
arr = np.array([-1,2,3,4,-4,9])
filter = arr%2 ==0
print(filter)
darr = arr[filter]
print(darr)

[False  True False  True  True False]
[ 2  4 -4]


#슬라이싱

In [54]:
arr = np.array([[1,2,3,],[4,5,6]])
arr.shape

(2, 3)

In [55]:
for i in range(2):
  for j in range(3):
    print(arr[i,j],end=',')
  print()

1,2,3,
4,5,6,


In [56]:
print(arr[0,1]) #가독성이 있다(강사님)
print(arr[0][1])

2
2


In [57]:
arr = np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [58]:
arr[3:10] #arr[3]~arr[10-1]

array([3, 4, 5, 6, 7, 8, 9])

In [59]:
arr[:5]

array([0, 1, 2, 3, 4])

In [60]:
arr[95:]

array([95, 96, 97, 98, 99])

In [61]:
arr[-1]

99

In [62]:
arr[90:-3]

array([90, 91, 92, 93, 94, 95, 96])

In [64]:
pre80 = arr[:len(arr)*4//5]
pre80

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [65]:
post20 = arr[len(arr)*4//5:]
post20

array([80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96,
       97, 98, 99])

#필터링 강화

In [70]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
scores = np.array([90,80,74,84,78,88,85])
filter = names=='Bob'
scores[filter]

array([90, 84])

In [72]:
texts = np.array(["hello, How are you?","where r u from?","RD GG","ready Go Go"])
filter = [True if "r" in text else False for text in texts]
filter
texts[filter]

array(['hello, How are you?', 'where r u from?', 'ready Go Go'],
      dtype='<U19')

[True if "r" in text else False for text in texts]
해당 컴프리헨션 설명

In [73]:
data = [i*i for i in range(10)]
print(data)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [75]:
data2 = [ i*i for i in range(10) if i%2==0] #조건 만족시키는 것만 나열
print(data2)

[0, 4, 16, 36, 64]


In [76]:
data3 = [i*i if i%2==0 else -(i*i) for i in range(10)]
print(data3)

[0, -1, 4, -9, 16, -25, 36, -49, 64, -81]
