<a href="https://colab.research.google.com/github/serinss/seSAC_Python_Class/blob/main/%ED%86%B5%EA%B3%84%EB%B6%84%EC%84%9D%EC%8B%9C%EA%B0%81%ED%99%94_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#www.numpy.org 레퍼런스 참고

import numpy as np

numpy는 선형 시퀀스를 배열 개체로 취급

In [2]:
ls = [1,2,3]
arr = np.array(ls)
print(arr)

[1 2 3]


In [8]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [9]:
print("구조: ",arr.shape) #shape로 행,열의 수를 알 수 있음 , 1x3 행렬
print("차원: ",arr.ndim) #1차원

구조:  (3,)
차원:  1


#다차원 배열

In [10]:
ls = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
arr = np.array(ls)
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
print("구조: ",arr.shape) # 4x3 행렬
print("차원: ",arr.ndim) #2차원

구조:  (4, 3)
차원:  2


#다양한 방법의 생성

In [14]:
z_arr = np.zeros(10) # zeros() : 0으로 초기화된 shape차원의 ndarray 객체 배열 반환 (ndarrya : Numpy의 핵심인 다차원 행렬 자료구조 클래스)
print(z_arr)
print("구조:",z_arr.shape) #1x10
print("차원:",z_arr.ndim)
print("원소 형식:",z_arr.dtype) #default : float

# ones() : 1로 초기화된 객체 배열 반환
# empry() : 초기화 되지 않은 객체 배열
# full() : 모든 값을 full 10으로 초기화

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
구조: (10,)
차원: 1
원소 형식: float64


In [15]:
z_arr = np.zeros(10, dtype=int) #int 값으로 변경 가능
print(z_arr)
print("구조:",z_arr.shape)
print("차원:",z_arr.ndim)
print("원소 형식:",z_arr.dtype)

[0 0 0 0 0 0 0 0 0 0]
구조: (10,)
차원: 1
원소 형식: int64


In [17]:
z_arr = np.zeros((2,3)) # 원소값이 모두 0인 2x3 행렬 
print(z_arr)
print("구조:",z_arr.shape)
print("차원:",z_arr.ndim)
print("원소 형식:",z_arr.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
구조: (2, 3)
차원: 2
원소 형식: float64


In [22]:
def view_arr_info(arr): # 자주 사용하는 구문들 함수로 만들어두기
  print(arr)
  print("구조:",arr.shape)
  print("차원:",arr.ndim)
  print("원소 형식:",arr.dtype)

In [23]:
z_arr = np.zeros((3,2,4),dtype=int) #3차원, 2x4
view_arr_info(z_arr)

[[[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]]
구조: (3, 2, 4)
차원: 3
원소 형식: int64


In [24]:
o_arr = np.ones(10)
view_arr_info(o_arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
구조: (10,)
차원: 1
원소 형식: float64


In [25]:
s_arr = np.arange(100) # arange() : 반열린구간 [start, stop) 에서 step 의 크기만큼 일정하게 떨어져 있는 숫자들을 array 형태로 반환해 준다. 
# stop 매개변수의 값은 필수 / start 는 step 은 필수 X
# start의 default : 0, step의 default : 1

view_arr_info(s_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
구조: (100,)
차원: 1
원소 형식: int64


In [26]:
s_arr = np.arange(50,100)
view_arr_info(s_arr)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]
구조: (50,)
차원: 1
원소 형식: int64


In [30]:
r_arr = np.random.randint(0,100,size=10,dtype=int) # 1~100 사이의 수로 1x10 행렬 만듦 + uint(=양수만)
view_arr_info(r_arr)

[38 58 78 55 41 35 48  3 17 80]
구조: (10,)
차원: 1
원소 형식: int64


#기본적인 사용

In [32]:
a1 = np.arange(1,100)
view_arr_info(a1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
구조: (99,)
차원: 1
원소 형식: int64


In [33]:
print(a1[4]) #인덱스를 통해 원소에 접근
a1[4]=9
print(a1[4])

5
9


In [34]:
print(a1[2:8]) #슬라이스를 통해 부분 원소 선택
print(a1[:8]) # 1~8
print(a1[8:]) # 8~99

[3 4 9 6 7 8]
[1 2 3 4 9 6 7 8]
[ 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32
 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56
 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80
 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [35]:
a1 = np.arange(0,100)
a2 = a1.reshape(5,20) # 5x20
view_arr_info(a2)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]
구조: (5, 20)
차원: 2
원소 형식: int64


In [38]:
print(a2[0]) # 인덱스 0인 원소(0행) : 리스트 출력
print(a2[0][2]) # 0행의 인덱스가 2인 원소값 출력

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
2


In [40]:
print(a2[0][-1]) #0행의 인덱스가 -1인 원소값 출력

19


#구조 변경

In [41]:
a1 = np.arange(100)
view_arr_info(a1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
구조: (100,)
차원: 1
원소 형식: int64


In [45]:
a2 = a1.reshape(20,-1)
view_arr_info(a2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]
구조: (20, 5)
차원: 2
원소 형식: int64


In [ ]:
a1 = np.arange(784)
view_arr_info(a1)

In [ ]:
a2 = a1.reshape(28,-1) # 28x28 행렬로 자동 정렬 (자동으로 batch_size를 조정)
view_arr_info(a2)

# reshape()의 '-1'이 의미하는 바는, 변경된 배열의 '-1' 위치의 차원은 "원래 배열의 길이와 남은 차원으로 부터 추정"이 된다는 뜻
# 즉, 행이나 열의 특정 차원을 기준으로 재배열하고 싶은 행이나 열의 개수가 있으면 나머지 차원의 개수는 '-1'로 해두면 알아서 자동으로 재배열을 해주니 편리한 기능

#쉬어가는 코너

In [57]:
from tensorflow import keras

In [58]:
data = keras.datasets.mnist.load_data() #손글씨 데이터를 다운로드

11501568/11490434 [==============================] - 0s 0us/step


In [59]:
train_data, test_data = data #학습용 데이터, 평가용 데이터로 분리
image_train, label_train = train_data #이미지, 실제값

In [61]:
print(image_train.shape) #28*28 6만개
print(label_train.shape)

(60000, 28, 28)
(60000,)


In [70]:
for r in range(28):
  for c in range(28):
    if(image_train[2][r][c] == 0):
      print("  ",end='')
    else:
      print("■",end='')
  print()
print("=> 작성한 숫자: " ,label_train[2])
# 해당 손글씨를 학습시킬 수 있다

                                                        
                                                        
                                                        
                                                        
                                                        
                                        ■■■          
        ■■                            ■■■          
        ■■                          ■■■■          
        ■■                          ■■■            
        ■■                          ■■■            
      ■■■                          ■■■            
      ■■■                        ■■■■            
      ■■■                        ■■■■            
      ■■■                  ■■■■■■              
      ■■■      ■■■■■■■■■■■■              
      ■■■■■■■■■■■■■■■■■                
        ■■■■■■■■          ■■■                
                                  ■■■                
                                  ■■■                
                   