<a href="https://colab.research.google.com/github/serinss/seSAC_Python_Class/blob/main/%ED%86%B5%EA%B3%84%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D_%EC%A3%BC%EC%9A%94_%EB%AA%A8%EB%93%88_%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

p.133 Numpy 기본

In [1]:
ls = [1,2,3,4,5]

ls_twice = []
for e in ls:
  ls_twice.append(e*2)
ls_twice

[2, 4, 6, 8, 10]

In [2]:
import numpy as np
arr = np.array(ls)
arr_twice = arr*2
arr_twice

array([ 2,  4,  6,  8, 10])

강한 wrapping

In [3]:
arr = np.arange(10000)
arr

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [4]:
arr = np.array(range(10000))
arr

array([   0,    1,    2, ..., 9997, 9998, 9999])

wrapping 이란?

In [6]:
def madd(a,b):
  return a+b

In [7]:
def msum(ls):
  s = 0
  for e in ls:
    s = madd(s,e)
  return s

In [9]:
def count(ls):
  cnt = 0
  for _ in ls:
    cnt += 1
  return cnt

In [11]:
ls=[1,2,3,8,4]
s = msum(ls)
l = count(ls)
print(f"평균:{s/l:.2f}")

평균:3.60


In [10]:
def average(ls):
  return msum(ls)/count(ls)