<a href="https://colab.research.google.com/github/serinss/seSAC_Python_Class/blob/main/%ED%86%B5%EA%B3%84%EB%B6%84%EC%84%9D%EC%8B%9C%EA%B0%81%ED%99%94_Numpy_more.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#행렬의 기본 연산

In [ ]:
import numpy as np

In [ ]:
ls1 = [1,2]
ls2 = [3,4]
ls3 = ls1 + ls2 
print(ls3)

[1, 2, 3, 4]


In [ ]:
s=0
for i in range(10):
  s += i

#assert 조건, '메시지' <-만든 함수를 테스트하는 용도로 사용한다.
assert s==55, "s는 45여야 합니다" #AssertionError:"입력한 구문" --> 에러 메세지 출력 기능(assert는 뒤의 조건이 True가 아니면 AssertError를 발생한다.)

In [ ]:
#ls 목록에 있는 요소의 합계를 구하는 함수
def calsum(ls):
  s = 0
  for e in ls:
    s += e
  return s

In [ ]:
assert calsum([1,2,3,2])==8, ""

In [ ]:
def add(l1,l2):
  assert len(l1) == len(l2), "더하기 연산을 위해서는 요소의 길이가 같아야 합니다." #구조가 같아야 덧셈 가능
  re = []
  for i in range(len(l1)):
    re.append(l1[i]+l2[i])
  return re

In [ ]:
ls1 = [1,2]
ls2 = [3,4]
ls3 = add(ls1,ls2)
print(ls3)

[4, 6]


In [ ]:
ls1 = [1,2]
ls2 = [3,4,5]
ls3 = add(ls1,ls2) #AssertionError: 더하기 연산을 위해서는 요소의 길이가 같아야 합니다.
print(ls3)

In [ ]:
#numpy로 하는 경우 직접 함수를 정의하지 않아도 된다.

n1 = np.array([1,2])
n2 = np.array([3,4])
n3 = n1 + n2
print(n3)

[4 6]


In [ ]:
n3 = n1 - n2
print(n3)

[-2 -2]


In [ ]:
n1 = np.array([1,2,3,4])
n2 = n1 * 3
print(n2)
#표준정규분포화 작업할 때 연산 사용

[ 3  6  9 12]


In [ ]:
n2 = n1/2
print(n2)

[0.5 1.  1.5 2. ]


In [ ]:
n1 = np.random.randint(1,1000,100,dtype=int)
print(n1)

[362 529 733 730 890 494 537 132 789 451 287 131 242 271 201 375 633 113
 369 711 302 638 986  94  61 400 575 299 893 814  60 142 213 140  63 714
 620 333 367 738  69 285 489 837 514 539 567 925 278 508 688 692 466 648
 203  60 943 472  26 608 241 145  45 796 428 847 924 825 155 425 471 505
 513 602 659 674  30 975 756 364 890 577 666 256 716 901 247 852 786 538
 805 692 625 421 714 702 651 365 658 581]


In [ ]:
n2 = n1 > 500
print(n2)

[False  True  True  True  True False  True False  True False False False
 False False False False  True False False  True False  True  True False
 False False  True False  True  True False False False False False  True
  True False False  True False False False  True  True  True  True  True
 False  True  True  True False  True False False  True False False  True
 False False False  True False  True  True  True False False False  True
  True  True  True  True False  True  True False  True  True  True False
  True  True False  True  True  True  True  True  True False  True  True
  True False  True  True]


In [ ]:
n3 = n1[n2]
print(n3) #True값만 추출

# https://nittaku.tistory.com/107
# 인덱스 자리 [] 에 마스크값(조건문, boolean array)을 넣으면 true에 해당하는 행 or 열만 뽑아내는 특징이 있다.

[529 733 730 890 537 789 633 711 638 986 575 893 814 714 620 738 837 514
 539 567 925 508 688 692 648 943 608 796 847 924 825 505 513 602 659 674
 975 756 890 577 666 716 901 852 786 538 805 692 625 714 702 651 658 581]


In [ ]:
n1 = np.array([[1,2],[3,4]])
n2 = np.array([4,5])
n3 = n1.dot(n2)
print(n3)

#내적

[14 32]


In [ ]:
n1 = np.array([1,2,3,4])
n2 = n1.reshape((2,2))
print(n2)

[[1 2]
 [3 4]]


In [ ]:
n3 = np.transpose(n2) #transport matrix : 전치행렬 - 축을 기준으로 요소를 바꾼다
print(n3)

[[1 3]
 [2 4]]


In [ ]:
n3 = np.invert(n2) #invert matrix : 역행렬아님 - 반전행렬(원소의 메모리)
print(n3)
# 요소별로 비트별 반전 또는 비트별 비트를 계산합니다.
# NOT 연산 (0->1,1->0)으로 반전시킨 값을 요소로 반환

[[-2 -3]
 [-4 -5]]


In [ ]:
n3 = np.linalg.inv(n2) #역행렬
print(n3)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
n4 = n2.dot(n3)
print(n4)
# 내적 -> 선형 회귀에서 방정식 계산 등에 활용 가능 (신경망)
# y = w1*x1 + w2*x2 + b

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


#통계 관련

In [ ]:
n1 = np.random.randint(1,100,30,dtype=int)
print(n1)

[17 43 95 81 55 84 88 13 31 19 94 35  7 10 81 59 14 14 96 51 83 96 60 71
 30 19 29 29 37 34]


In [ ]:
print("길이:",len(n1))

길이: 30


In [ ]:
print("평균:",n1.mean())

평균: 52.266666666666666


In [ ]:
n2 = n1 - n1.mean()
print("수평 이동한 후 평균:",n2.mean())

수평 이동한 후 평균: 9.473903143468002e-16


In [ ]:
print("최대값 위치",n1.argmax())
print("최대값:",n1[16])
print("최대값:",n1.max())

최대값 위치 26
최대값: 62
최대값: 95


In [ ]:
print("표준편차:",n1.std())

표준편차: 25.451828137789153


In [ ]:
n2 = n1/n1.std()
print("스케일 조절한 후 표준편차:",n2.std())

스케일 조절한 후 표준편차: 0.9999999999999998


In [ ]:
print("최솟값:",n1.min())
print("중앙값:",np.median(n1))
print("1/4분위값:",np.percentile(n1,25))
print("3/4분위값:",np.percentile(n1,75))

최솟값: 7
중앙값: 40.0
1/4분위값: 21.5
3/4분위값: 81.0


In [ ]:
print("누적 합:", np.cumsum(n1))

누적 합: [  58  148  192  261  336  390  416  481  535  584  647  732  799  807
  820  893  955 1009 1032 1039 1067 1113 1161 1194 1272 1341 1436 1468
 1561 1568]


In [ ]:
n1 = np.arange(1,10)
print(n1)
print("누적 곱:",np.cumprod(n1))

[1 2 3 4 5 6 7 8 9]
누적 곱: [     1      2      6     24    120    720   5040  40320 362880]
